version: '3.8'

services:
  backend:
    build:
      context: ./Techdome-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./Techdome-backend:/app
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000

  frontend:
    build:
      context: ./Techdome-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Techdome-frontend:/app
    environment:
      - NODE_ENV=development
